from vikingsClasses import Soldier, Viking, Saxon, War
import random

war_1 = War()  # creating a War() object

number_of_vikings = input("How many Vikings?")
number_of_saxons = input("How many Saxons?")

list_of_names = ["Steve", "Dave", "Bill", "Mike", "Bob","Tom", "Jim", "John",
                "Pete", "Frank","Joe", "Dan", "Rick", "Greg", "Mark","Chuck",
                "Todd", "Brad", "Carl", "Jeff","Gary", "Ted", "Ron", "Larry", "Ken"]
list_of_used_names = []

for _ in range(int(number_of_vikings)):
    name = random.choice(list_of_names)
    if name in list_of_used_names:                                                                          # Silly logic to deal with duplicate names
        war_1.addViking(Viking(name+"'s identical brother",10, 2))
        list_of_used_names.append(name+"'s identical brother")
        list_of_names.append(name+"'s identical brother")
        list_of_names.remove(name)
    else:                                                                                                   # Creating Vikings without duplication of names in list_of_names
        war_1.addViking(Viking(name,10, 2))                                                                 # Stats of Vikings
        list_of_used_names.append(name)
        list_of_names.append(name+"'s identical brother")
        list_of_names.remove(name)
    

for _ in range(int(number_of_saxons)):                                                                      # Creation of Saxons
    if _ >= 0:                                                                                              # if _: would lead to one fewer saxon as we start from 0
        war_1.addSaxon(Saxon(5, 1))

list_of_viking_names = [_.name for _ in war_1.vikingArmy]                                                   # Generates a list extracting the name of each viking by calling the viking.name atribute

if len(list_of_viking_names) > 1:                                                                           # fstring formatting of names
    viking_names = ','.join(list_of_viking_names[:-1]) + f" and {list_of_viking_names [-1]}"
elif len(list_of_viking_names) == 1:
    viking_names = "".join(list_of_viking_names)

print(f"{len(war_1.saxonArmy)} Saxon(s) versus {len(war_1.vikingArmy)} Viking(s) called: {viking_names}")   # Introduction to the game

number_of_rounds = int(input("how many rounds? Enter -1 for all."))                                         # User input of number of rounds to play, -1 triggers the while lopp so the game goes to completion
round_counter = 0

if number_of_rounds == -1:                                                                                  # Core logic of the game,
    while (war_1.vikingArmy and war_1.saxonArmy) != []:                                                     # For as long as neither army list is empty, run the while loop of war_1 attack methods
        round_counter += 1                                                                                  # Incrementing round counter to provide narration during the game
        war_1.vikingAttack()                                                                                
        war_1.saxonAttack()        
        print(f"{war_1.showStatus()} after {round_counter} rounds!")                                        # Narration of the gamestate using the showStatus method on war_1
else:
    for _ in range(number_of_rounds):
        round_counter += 1 
        war_1.vikingAttack()
        war_1.saxonAttack()
        print(f"{war_1.showStatus()} after {round_counter} rounds!") 
        if war_1.showStatus() != "Vikings and Saxons are still in the thick of battle.":                    #checking result of war_1 showStatus method to decide when to break for loop
            break

v_health = sum (_.health for _ in war_1.vikingArmy)                                                         # Created a variable for total army health by summing each of the .health attributes
s_health = sum (_.health for _ in war_1.saxonArmy)                                                          # of each saxon and viking object in the lists generated by the war.vikingArmy
                                                                                                            # and war.saxonArmy methods


list_of_dead_viking_names = [_.name for _ in war_1.valhalla]                                                ## Added valhalla atribute to War() class to provide a list of dead vikings.

if len(list_of_dead_viking_names) > 1:                                                                      ## fstring formatting of the list of dead vikings
    dead_viking_names = ','.join(list_of_dead_viking_names[:-1]) + f" and {list_of_dead_viking_names [-1]}"
elif len(list_of_dead_viking_names) == 1:
    dead_viking_names = "".join(list_of_dead_viking_names)
else:
    dead_viking_names = "that no vikings died"                

                                                                                                            # Game summary where the number of survivors, total remaing army health
                                                                                                            # and names of the fallen are given.       
print(f"""Game Over,  
{len(war_1.saxonArmy)} Saxon(s) survive with {s_health} total health remaining, 
while {len(war_1.vikingArmy)} Viking(s) survive with {v_health} total health remaining.""")

print(f"Never forget: {dead_viking_names}")